-- Persisted usage analytics, additive to the live in-memory /api/monitoring/presence view.
--   * users.last_seen_at  — bumped on every successful, entitled WebSocket open ("is this user alive?").
--   * connection_events    — append-only log, one row per successful open, aggregated at read time by
--                            /api/monitoring/usage. High-volume, so a compact BIGINT identity PK (unlike
--                            the low-volume UUID-keyed entities elsewhere). No retention job — manual
--                            cleanup later if it grows.

ALTER TABLE users ADD COLUMN last_seen_at TIMESTAMPTZ;   -- nullable: NULL = never seen under new tracking

CREATE TABLE connection_events (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    connected_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- The aggregation query is a range scan over connected_at.
CREATE INDEX idx_connection_events_connected_at ON connection_events(connected_at);
